import imgTest from '../assets/card-test.jpg';

export const cardProductData = [
	{
		id: 1,
		text: 'Товар 1',
		src: imgTest,
		category: 'Одежда',
		price: '4000Р / 1 день',
		date: 'Сегодня 13:08',
		location: 'Москва',
	},
	{
		id: 2,
		text: 'Товар 2',
		src: imgTest,
		category: 'Обувь',
		price: '3000Р / 1 день',
		date: 'Сегодня 15:30',
		location: 'Санкт-Петербург',
	},
	{
		id: 3,
		text: 'Товар 3',
		src: imgTest,
		category: 'Аксессуары',
		price: '2000Р / 1 день',
		date: 'Вчера 18:45',
		location: 'Екатеринбург',
	},
	{
		id: 4,
		text: 'Товар 4',
		src: imgTest,
		category: 'Электроника',
		price: '5000Р / 1 день',
		date: 'Сегодня 10:20',
		location: 'Казань',
	},
	{
		id: 5,
		text: 'Товар 5',
		src: imgTest,
		category: 'Косметика',
		price: '1500Р / 1 день',
		date: 'Сегодня 12:00',
		location: 'Новосибирск',
	},
	{
		id: 6,
		text: 'Товар 6',
		src: imgTest,
		category: 'Спорт',
		price: '3500Р / 1 день',
		date: 'Сегодня 17:10',
		location: 'Ростов-на-Дону',
	},
	{
		id: 7,
		text: 'Товар 7',
		src: imgTest,
		category: 'Книги',
		price: '1000Р / 1 день',
		date: 'Вчера 22:30',
		location: 'Красноярск',
	},
	{
		id: 8,
		text: 'Товар 8',
		src: imgTest,
		category: 'Игрушки',
		price: '2500Р / 1 день',
		date: 'Сегодня 16:45',
		location: 'Уфа',
	},
];
